language: python
python:
  - 2.7
cache:
  apt: true
  directories:
  - $HOME/.pip-cache
virtualenv:
  system_site_packages: true
before_install:
  - export CLONE=$PWD
  - export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib:$LD_LIBRARY_PATH
  - export DISTRIBUTIONS_USE_PROTOBUF=1
  - export MAKEFLAGS="-j 2 -S"
  - export LOOM_THREADS=2
  - export OMP_NUM_THREADS=2
  - env
  - pip uninstall numpy -y || echo 'numpy not installed'
  - sudo apt-get update -qq
  - sudo ./requirements.sh
  - cd
  - rm -rf distributions
  - git clone https://github.com/posterior/distributions.git
  - cd distributions
  - pip install -r requirements.txt
  - make install
  - cd $CLONE
  - pip install -r requirements.txt
install:
  - make install
  - pip freeze
script:
  - NOSE_PROCESSES=0 make small-test
